/**
* @package     Heurist academic knowledge management system
* @link        http://HeuristNetwork.org
* @copyright   (C) 2005_2020 University of Sydney
* @author      Artem Osmakov   <artem.osmakov@sydney.edu.au>
* @license     http://www.gnu.org/licenses/gpl_3.0.txt GNU License 3.0
* @version     4.0
*/

/*
* Licensed under the GNU License, Version 3.0 (the "License"); you may not use this file except in compliance
* with the License. You may obtain a copy of the License at http://www.gnu.org/licenses/gpl_3.0.txt
* Unless required by applicable law or agreed to in writing, software distributed under the License is
* distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied
* See the License for the specific language governing permissions and limitations under the License.
*/

regional['ru'] = {
    language: 'Langue',
    'Databases': 'Bases de données,
    'Design database': 'Concevoir une base de données,
    'Import data': 'Importer des données,
    'Files in situ': 'Dossiers in situ',
    'Report bug': 'Signaler un bug',
    'About': 'A propos...',
    'Confirmation':'Confirmation',
    'Info':'Info',

    'Register': 'S'inscrire',
    'Registration': 'Inscription',
    'Login': 'Connexion',
    'Please log in': 'Veuillez vous connecter,
    'Please contact to register':'Veuillez contacter le propriétaire de la base de donnée pour vous inscrire ',
    'Log out' : 'Déconnexion',
    'Manage': 'Gérer',
    'Sort': 'Trier',
    'Search': 'Chercher',
    'Search result': 'Résultat de recherche',
    'Merge': 'Fusionner ? Combiner?,
    'Rate': 'Оценить',
    'Relate to': 'Связать с',
    'Access': 'Accès',
    'Notify': 'Notifier',
    'Embed / link': 'Intégrer / lier',
    'Export': 'Exporter',
    'Import': 'Importer',


    'Username': 'Login,
    'Password': 'Mot de passe',
    'Remember me': 'Se souvenir de moi,
    'Forgotten your password?': 'Mot de passe oublié ?',
    'Click here to reset it': 'Réinitialiser votre mot de passe',
    'Enter your username OR email address below and a new password will be emailed to you.':'Saisissez votre login ou votre adresse e-mail de récuperation"
,
    'Reset password': 'Réinitialiser mot de passe',
    'Email to':'Contact',
    'User information has been saved successfully':'Les informations de l'utilisateur ont été sauvegardées avec succès',

    'Database': 'Base de données',
    'Select database': 'Choisir la base de données',
    'My User Info' : 'Mon profil utilisateur',
    'My Groups' : 'Mes groupes',
    'Manage Tags' : 'Gérer mes étiquettes',
    'Tags' : 'Étiquettes',
    'Manage Files': 'Gérer mes dossiers',
    'Manage Reminders' : 'Gérer mes rappels',
    'Set Ratings' : 'Définir mes notations',
    'No Rating': 'Aucune notation,

    'Name': 'Titre',
    'Description': 'Description',
    'Size': 'Taille',
    'Type': 'Type',

    'search': 'c hercher',
    'all records': 'среди всех записей',
    'my bookmarks': 'mes marque-pages',
    'in current': 'в текущем',
    'search option': 'варианты поиска',
    'search assistant': 'assistant de recherche',
    'Any record type': 'Любой тип записи',
    'Any field type': 'Tout type de champ',
    'Record type': 'Тип записи',
    'Field': 'Champ',
    'Contains': 'Contient',
    'Is': 'Est',
    'Sort By': 'Trier par',
    'Sort Ascending': 'Trier en ordre croissant',
    'fields':'champs',

    'add': 'ajouter',
    'Add New Record' : 'Добавить запись',
    'tags': 'êtiquettes',
    'share': 'partager',
    'more': 'plus',
    'edit': 'modifier',
    'options': 'options',

    'by name': 'par titre',
    'by usage': par usage',
    'by date': 'par date',
    'by size': 'par taille,
    'by type': 'par type',
    'marked': 'marqué',

    'list':'liste',
    'icons':'icônes',
    'thumbs':'vignettes',
    'thumbs3':'превью',

    'first':'premier',
    'previous':'précédent',
    'next':'suivant',
    'last':'dernier',
    'records per request':'записей в запросе',

    'Manage tags': 'Gérer mes tags',
    'Create new tag': 'Créer un nouveau tag,
    'Add Tag': 'Ajouter un tag',
    'Edit Tag': 'Éditer le tag',
    'Define new tag that replaces old ones': 'Définir un nouveau tag qui remplace les anciens,
    'Length of tag must be more than 2.': 'La longueur du tag doit être supériure à 2',
    'Assign selected tags': 'Assigner les tags selectionnés',
    'Personal Tags':'Mes tags personnels,
    'Delete selected tags': 'Supprimer les tags selectionnés',



    'Preferences' : 'Préférences',
    'Layout configuration file': Fichier de configuration de la mise en page',
    'Language':'Langue',
    'Theme':'Thème',
    'Open edit in new window':'Ouvrir la fenêtre d'édition',
    'When exiting record edit, prompt for tags if no tags have been set':'Перед сохранением предлагать определить ярлыки',
    'Reload page to apply new settings?':'Recharger la page pour appliquer les nouveaux paramètres ?',

    'Click to save current search':'Cliquez pour sauvegarder la recherche en cours,
    'My Bookmarks': 'Mes marque-pages,
    'My Searches': 'Mes recherches',
    'Predefined searches': 'Recherches prédefinies,
    'Recent changes': 'Changements récents,
    'All records': 'Tous les records',
    'All (date order)': 'Tous (ordonnés par date)',
    'Edit saved search': 'Éditer la recherche sauvegardée,
    'Delete saved search': 'Supprimer la recherche sauvegardée,
    'Manage Saved Searches': 'Gérer mes recherches sauvegardées,
    'Create new saved search': 'Créer une nouvelle recherche sauvegardée',

    'Database Summary': 'Résumé de la base de données',
    'RuleSets': 'Jeux de règles',


    'Delete? Please confirm': 'Supprimer ? Veuillez confirmer',

    'select record': 'Selectionner un ,

    'Leave blank for no change': Laisser vide pour ne pas effectuer un changement,
    'Passwords are different': 'Les mots de passe ne correspondent pas,
    'Wrong email format': 'Mauvais format d'e-mail',
    'Wrong user name format': 'Mauvais format de nom d'utilisateur',
    'Wrong password format': 'Mauvais format de mot de passe',
    'Missing required fields': 'Champs obligatoires manquants',
    'length must be between': 'La longueur doit être comprise entre',
    'required field': 'Champ obligatoire',
    
    //========================  2021_07_08 =======================

    //common words
    'Close': 'Fermer',
    'Settings': 'Paramètres',
    'Help': 'Aide',
    'Error': 'Erreur',
    'records': 'записей',
    'loading': 'chargement',
    'preparing': 'préparations',
    'explanations': 'explications',
    'Show data': 'Montrer les données',
    'Actions': 'Actions',
    'Embed': 'Intégrer',
    'Clear': 'Effacer',
    'Warning': 'Alerte',    
    'Cancel': 'Annuler',
    'Record Info': 'Данные записи',
    'Add': 'Ajouter',
    'Assign': 'Assigner',
    'Apply': 'Appliquer',
    'Abort': 'Abandonner',
    'Define': 'Définir',
    'Edit': 'Éditer',
    'Delete': 'Supprimer',
    'Create': 'Créer',
    'Confirm': 'Confirmer',
    'Proceed': 'Continuer',
    'Continue: 'Continuer',
    'Go': 'Aller',
    'Yes': 'Oui',
    'OK': 'OK',
    'No': 'Non',
    'Save': 'Sauvegarder',
    'Save data': 'Sauvegarder les données',
    'Ignore and close': 'Ignorer et fermer',
    'Drop data changes': 'Abandonner les changements effectués aux données,
    'Manage': 'Gérer',
    'Select': 'Selectionner',
    'Configure': 'Configurer',
    
    'Show context help': 'Контекстная помощь',
    'Heurist context help': 'Контекстная помощь',
    'Sorry context help was not found': 'Помощь не найдена',
    
    //main menu 
    'Admin': 'Админ',
    'Design': 'Дизайн',
    'Populate': 'Наполнение',
    'Explore': 'Искать',
    'Publish': 'Публикация',
    'Profile': 'Профиль',
        
    add_new_record: 'Новая запись', //header for New record
    add_new_record2: 'Ввод', // prefix before rectype name
    
    //explore menu
    'Filters': 'Фильтры',
    'Recent': 'Недавние',
    'All': 'Все',
    'Entities': 'Типы записей',
    'Saved filters': 'Каталог фильтров',
    'Build': 'Создать',
    'Filter builder': 'Условия поиска',
    'Facets builder': 'Многогранный поиск',
    'Save filter': 'Добавить фильтр',
    'Advanced': 'Дополнительно',
    'Rules': 'Каскадный поиск',
    
    //admin menu
    'Database': 'База данных',
        menu_database_browse: 'Открыть',
        menu_database_create: 'Новая',
        menu_database_clone: 'Клонировать',
        menu_database_delete: 'Удалить',
        menu_database_clear: 'Очистить',
        menu_database_rollback: 'Восстановить',
        menu_database_register: 'Зарегистрировать',
        menu_database_properties: 'Свойства',
        
        menu_database_browse_hint:'Найти и открыть другую базу Heurist в новом окне',
        menu_database_create_hint:'Созадть новую базу данных _ все основные элементы структуры будут добавлены автоматически',
        menu_database_clone_hint:'Создать копию текущей базы со всеми данными, загружеными файлами, шаблонами итп',
        menu_database_delete_hint:'Удалить текущую базу полностью _ не может быть отменено, хотя данные будут скопированы в дамп и могут быть восстановлены сисадмином',
        menu_database_clear_hint:'Clear all data (records, values, attached files) from the current database. Database structure _ record types, fields, terms, constraints _ is unaffected',
        menu_database_rollback_hint:'Selectively roll back the data in the database to a specific date and time',
        menu_database_register_hint:'Зарегистировать эту базу в Heurist Master Index _ это сделает доступным импорт элементов структуры (но не данных) в других базах',
        menu_database_properties_hint:'Редактировать описание базы данных и определить некторые глобальные установить . Recommended to provide a self_documenting database',
        
    'Manage Users': 'Пользователи',
        menu_profile_groups: 'Группы',
        menu_profile_users: 'Пользователи',
        menu_profile_import: 'Импорт профиля',
        menu_profile_groups_hint: 'List of groups you are member of',
        menu_profile_users_hint: 'Add and edit database users, including authorization of new users. Use Manage Workgroups to allocate users to workgroups and define roles within workgroups',
        menu_profile_import_hint: 'Import users one at a time from another database on the system, including user name, password and email address _ users are NOT assigned to workgroups',
    'Utilities': 'Утилиты',
        menu_profile_files: 'Управление файлами',
        menu_profile_preferences: 'Настройки профиля',
        menu_structure_verify: 'Проверка целостности данных',
        menu_structure_duplicates: 'Найти повторения',
        menu_manage_rectitles: 'Обновить заголовки',
        menu_profile_files_hint: 'Управление загружеными файлами и удаленными медиа ресурсами',
        menu_profile_preferences_hint: 'Показать и редактировать настройки профиля',
        menu_structure_verify_hint: 'Найти ошибки в структуре базы (неправильные типы записей, полей и словарей) и записи с неправильной структурой и ошибными данными (ссылки, пропущеные данные итп)',
        menu_structure_duplicates_hint: 'Нечеткий поиск для определения записей которые могут содержать идентичные данные',
        menu_manage_rectitles_hint: 'Обновить заголовки для всех записей',
    'Server Manager': 'Управление сервером',
        menu_admin_server: 'Базы данных',
        menu_admin_server_hint: 'Операции для всех баз данных на этом сервере',
        
    //design menu
    'Modify': 'Изменить структуру',
        menu_structure_rectypes: 'Типы записей',
        menu_structure_vocabterms: 'Словари',
        menu_structure_fieldtypes: 'Базовые поля',
        menu_structure_import: 'Импорт шаблонов',
        menu_lookup_config: 'External lookups', // needs replacing
        menu_structure_summary: 'Визуализация',
        menu_structure_refresh: 'Перегрузить структуру',
    
        menu_structure_rectypes_hint: 'Добавить или модифицировать типы записей',
        menu_structure_vocabterms_hint: 'Добавить или модифицировать словари',
        menu_structure_fieldtypes_hint: 'Редактировать определения базовых полей используемых в типах записей (часто одновременно в нескольких типах)',
        menu_structure_import_hint: 'Выборочно импортировать типы записей, базовые поля и словари из других баз Heurist',
        menu_structure_summary_hint: 'Визуализация внутренних связей между типами записей в базе (указателей и отношений)',
        menu_structure_refresh_hint: 'Очистить и перегрузить структру базы Heurist в вашем браузере. Используйтк чтобы обновить списки и селекторы в случае если изменени не отображаются',
    
    'Setup': 'Настройки',
        menu_manage_dashboards: 'Панель ярлыков',
        menu_manage_archive: 'Архивировать базу',
        menu_manage_dashboards_hint: 'Определить ярлыки для быстрого доступа к функциям',
        menu_manage_archive_hint: 'Архивировать все данные как SQL дамп и XML файлы, а также загруженые файлы, шаблоны и документы, в ZIP архив который моэет быть скачен по ссылке',

    'Download': 'Скачать',
        menu_manage_structure_asxml: 'Структуру как XML',
        menu_manage_structure_assql: 'Структуру как Text',
        menu_manage_structure_asxml_hint: 'Список определений типов записи и полей в XML формате (HML - Heurist Markup Language)',
        menu_manage_structure_assql_hint: 'Список определений типов записи и полей в форме для использования SQL выражениях',
        
    //populate menu
    'Upload Files': 'Загрузить файлы',
        menu_import_csv: 'Текст / CSV',
        menu_import_zotero: 'Zotero библиография',
        menu_import_xml: 'Heurist XML/JSon',
        menu_import_kml: 'KML',
        menu_import_get_template: 'Скачать шаблон (XML)',
        menu_import_csv_hint: 'Import data from delimited text file. Supports matching, record creation, record update.',
        menu_import_zotero_hint: 'Synchronise with a Zotero web library _ new records are added to Heurist, existing records updated',
        menu_import_xml_hint: 'Import records from another database',
        menu_import_kml_hint: 'Import KML files (geographic data in WKT can be imported from CSV &amp; tab delimited files)',
        menu_import_get_template_hint: 'Get XML template that describes database structure', 
    'Media Files': 'Медиа файлы',
        menu_files_upload: 'Загрузить медиа файлы',
        menu_files_index: 'Проиндексировать',
        menu_files_upload_hint: 'Upload multiple files and/or large files to scratch space or image directories, delete and rename uploaded files',
        menu_files_index_hint: 'Index files on the server and create multimedia records for them (reads and creates FieldHelper manifests)',
    
    //publish menu
    'Website': 'Веб сайт',
        menu_cms_create: 'Создать',
        menu_cms_edit: 'Править',
        menu_cms_edit_new: 'Править (новое)',
        menu_cms_view: 'Просмотр',
        menu_cms_embed: 'Отдельная веб страница',
        menu_cms_create_hint: 'Create a new CMS website, stored in this database, with widgets to access data in the database',
        menu_cms_edit_hint: 'Edit a CMS website defined in this database',
        menu_cms_view_hint: 'View a CMS website defined in this database',
        menu_cms_embed_hint: 'Create or edit a standalone web page in this database. May contain Heurist widgets. Provides code to embed page in an external iframe.',
        
        'Website Editor': 'Редактор вебсайта',
        'Sitewide Settings': 'Настройки сайта',
        'Current Page': 'Текущая страница',
       'Page Editor': 'Редактор страницы',
       
    'Standalone page': 'Отдельная веб страница',
        menu_cms_create_page: 'Создать',
        menu_cms_edit_page: 'Править',
        menu_cms_view_page: 'Просмотр',
        
    'Export': 'Экспорт',
        menu_export_csv: 'CSV',
        menu_export_hml_resultset: 'XML',
        menu_export_json: 'JSON',
        menu_export_geojson: 'GeoJSON',
        menu_export_kml: 'KML',
        menu_export_gephi: 'GEPHI',
        menu_export_csv_hint: 'Export records as delimited text (comma/tab), applying record type',
        menu_export_hml_resultset_hint: 'Generate HML (Heurist XML format) for current set of search results (current query + expansion)',
        menu_export_json_hint: 'Generate JSON for current set of search results (current query)',
        menu_export_geojson_hint: 'Generate GeoJSON_T for current set of search results (current query)',
        menu_export_kml_hint: 'Generate KML for current set of search results (current query + expansion)',
        menu_export_gephi_hint: 'Generate GEPHI for current set of search results (current query + expansion)',
    
    'Safeguard': 'Резервная копия',
        
    //My profile menu
    menu_profile_tags: 'Управления тегами',
    menu_profile_reminders: 'Управление напоминаниями',
    menu_profile_info: 'Мой профиль',
    menu_profile_logout: 'Выход',
    menu_profile_tags_hint: 'Удаление, модификация, переименование ваших личных и групповых тегов (ярлыков)',
    menu_profile_reminders_hint: 'Просмотр и удаления автоматических сообщений/ссылок на ваши записи',
    menu_profile_info_hint: 'Информация о вашем пользовательском профиле',
    menu_profile_logout_hint: '',
        
    //HELP menu
    HELP: 'ПОМОЩЬ',
        menu_help_online: 'Документация',
        menu_help_website: 'Heurist Network вебсайт',
        menu_help_online_hint: 'Исчерпывающая помощь и документация по Heurist',
        menu_help_website_hint: 'Heurist Network вебсайт - основной источник  информации, услуг и контактов', 
    CONTACT: 'КОНТАКТЫ',
        menu_help_bugreport: 'Отчет об ошибке / запрос новых функций',
        menu_help_emailteam: 'Команда Heurist',
        menu_help_emailadmin: 'Системны администратор',
        menu_help_acknowledgements: 'Признательности',
        menu_help_about: 'О приложении',
        menu_help_bugreport_hint: 'Послать email to the Heurist team such as additional bug information, comments or new feature requests',
        menu_help_emailteam_hint: '',
        menu_help_emailadmin_hint: 'Послать email to the System Adminstrator for this installaton of Heurist - typically for probelms with this installation',
        menu_help_acknowledgements_hint: '',
        menu_help_about_hint: 'Версия, Авторы, Права, Лицензия',
    
    menu_subset_set: 'Подмножество',
    menu_subset_set_hint: 'Сделать текущий поиск активным - все последующие поиски будут проходить в этом подмножестве записей',
    'Click to revert to whole database': 'Нажмите чтобы сбросить подмножество и искать по всей базе',
    'SUBSET ACTIVE': 'ПОДМНОЖЕСТВО',
    'Current subset': 'Активно',
    
    //END main menu
    
    //resultList --------------------
    
    'Selected': 'Sélectionner',
        menu_selected_select_all: 'Tout sélectionner',
        menu_selected_select_all_hint: 'Sélectionner tous les enregistrements de la liste',
        menu_selected_select_none: 'Déselectionner',
        menu_selected_select_none_hint: 'Déselectionner tous les enregistrements de la liste',
        menu_selected_select_show: 'Afficher en tant que résultat d'une requête',
        menu_selected_select_show_hint: 'Afficher les enregistrements sélectionnés dans une nouvelle fenêtre de recherche',
        menu_selected_tag: 'Tags',
        menu_selected_tag_hint: 'Sélectionnez un ou plusieurs enregistrements, puis cliquez pour ajouter ou supprimer les tags',
        menu_selected_rate: 'Notes',
        menu_selected_rate_hint: 'Sélectionnez un ou plusieurs enregistrements, puis cliquez pour ajouter une note de 1 à 5',
        menu_selected_bookmark: 'Marque-pages',
        menu_selected_bookmark_hint: 'Sélectionnez un ou plusieurs enregistrements, puis cliquez pour ajouter un marque-page',
        menu_selected_unbookmark: 'Supprimer les marque-pages',
        menu_selected_unbookmark_hint: 'Sélectionnez un ou plusieurs enregistrements, puis cliquez pour supprimer les marque-pages',
        menu_selected_merge: 'Fusionner',
        menu_selected_merge_hint: 'Sélectionnez un ou plusieurs enregistrements, puis cliquez pour fusionner/gérer les doublons',
        menu_selected_delete: 'Supprimer',
        menu_selected_delete_hint: 'Sélectionnez un ou plusieurs enregistrements, puis cliquez pour les supprimer',
    'Collected': 'Collectés',
    'Collect': 'Collecter',
        menu_collected_add: 'Ajouter',
        menu_collected_add_hint: 'Sélectionnez un ou plusieurs enregistrements, puis cliquez pour les ajouter à la collection',
        menu_collected_del: 'Retirer',
        menu_collected_del_hint: 'Sélectionnez un ou plusieurs enregistrements, puis cliquez pour les retirer à de la collection',
        menu_collected_clear: 'Vider',
        menu_collected_clear_hint: 'Vider la collection',
        menu_collected_save: 'Enregistrer sous ...',
        menu_collected_save_hint: 'Enregistrer la liste des résultats dans la collection',
        menu_collected_show: 'Montrer en tant que recherche',
        menu_collected_show_hint: 'Montrer la liste des résultats dans la collection',
            collection_limit: 'The number of selected records is above the limit in ',
            collection_select_hint:  'Veuillez sélectionner au mons un enregistrement pour l'ajouter à la collection',
            collection_select_hint2: 'Veuillez sélectionner au mons un enregistrement pour le retirer de la collection',
            collection_url_hint: 'Les collections sont sauvegardées comme une liste d'identifiants. L'URL générée par cette collection va dépasser la limite possible pour une URL (2083 caractères). Veuillez enregistrer la colection en tant que recherche sauvegardée (qui autorise un plus grand nombre d'enregistrements), ou sélectionnez moins d'enregistrements.',
        
    'Recode': 'Modifier',
        menu_selected_value_add: 'Ajouter une valeur',
        menu_selected_value_add_hint: 'Ajouter une valeur pour les résultats trouvés',
        menu_selected_value_replace: 'Remplacer une valeur',
        menu_selected_value_replace_hint: 'Remplacer une valeur dans les enregistrements trouvés',
        menu_selected_value_delete: 'Supprimer une valeur',
        menu_selected_value_delete_hint: 'Supprimer une valeur dans les enresgitrements trouvés',
        menu_selected_add_link: 'Relier : lien',
        menu_selected_add_link_hint: 'Ajouter un nouveau lien ou créer une nouvelle relation entre des enregistrements',
        menu_selected_rectype_change: 'Changer le type d'enregistrement',
        menu_selected_rectype_change_hint: 'Changer le type d'enregistrement pour les enregistrements trouvés',
        menu_selected_extract_pdf: 'Extraire le texte d'un document PDF',
        menu_selected_extract_pdf_hint: 'Extract text from PDExtraire le texte d'un document PDF (expérimental)',
    'Shared': 'Partager',
        menu_selected_notify: 'Notification (courriel)',
        menu_selected_notify_hint: 'Sélectionner un ou plusieurs enregistrement puis cliquer pour envoyer une notification',
        menu_selected_email: 'Envoyer un courriel',
        menu_selected_email_hint: 'Envoyer un courriel aux personnes ou aux institutions décrites dans l'enregistrement sélectionné',
        menu_selected_ownership: 'Propriété / visibilité',
        menu_selected_ownership_hint: 'Sélectionner un Select one or more records, then click to set workgroup ownership and visibility',
    'Reorder': 'Réorganiser',
    menu_reorder_hint: 'Allows manual reordering of the current results and saving as a fixed list of ordered records',
    menu_reorder_title: 'Drag records up and down to position, then Save order to save as a fixed list in this order',
    menu_reorder_save: 'Save Order',
    
    //
    resultList_select_record: 'Merci de sélectionner au moins un enregistrement pour cette action',
    resultList_select_record2: 'Merci de sélectionner au moins deux enregistrement pour identifier ou fusionner des doublons',
    resultList_select_limit: 'Le nombre d'enregistrements sélectionnés est supérieur à la limite de ',
    resultList_noresult: 'Aucun résultat. Merci de modifier la recherche ou le filtre pour trouver au moins un enregistrement.',
    resultList_empty_remark: 'Aucun enregistrement ne correspond au critère (des enregistrements existent peut-être mais n'ont peut-être pas été rendus publics ou visible pour votre profil utilisateur)',
    resultList_private_record: 'Cet enregistrement n'est pas visible de manière publique - les utilisateurs doivent être connectés pour le voir',
    'private - hidden from non-owners': 'privé (masqué pour les non-propriétaires)',
    'visible to any logged-in user': 'visible pour tous les utilisateurs connectés',
    'pending (viewable by anyone, changes pending)': 'en cours (visible par tout le monde, changements en cours)',
    'public (viewable by anyone)': 'public (visible par tout le monde)',
    'show selected only': 'montrer uniquement la sélection',
    'Single lines': 'Lignes simples',
    'Single lines with icon': 'Lignes simples avec icône',
    'Small images': 'Images de petite taille',
    'Large image': 'Images de grande taille',
    'Record contents': 'Contenu de l'enregistrement',
    resultList_view_content_hint1: 'Cette alerte se déclenche s'il y a plus de 10 enregistrements',
    resultList_view_content_hint2: 'Vous avez sélectionné',
    resultList_view_content_hint3: 'enregistrements. Ce mode d'affichage charge l'ensemble des informations pour chaque enregistrement. Le chargement et l'affichage de toutes ces informations peut prendre un temps important.',
    resultList_action_edit: 'Cliquer pour éditer l'enregistrement',
    resultList_action_edit2: 'Cliquer pour éditer l'enregistrement (s'ouvre dans un ouvel onglet)',
    resultList_action_view: 'Cliquer pour éditer l'enregistrement (s'ouvre dans un fenêtre pop-up)',
    resultList_action_view2: 'Cliquer pour suivre le lien externe (s'ouvre dans une nouvelle fenêtre)',
    resultList_action_map: 'Cliquer pour afficher/masquer sur la carte',
    resultList_action_dataset: 'Télécharger le jeu de données',
    resultList_action_embded: 'Cliquer pour incorporer',
    resultList_action_delete: 'Cliquer pour supprimer',
   
    resultList_action_delete_hint: 'Delete map document. Associated map layers and data sources retain',
    'Password reminder': 'Aide-mémoire pour le mot de passe',
   
    //END resultList

    //search - filters
    'Filter': 'Filtre',
    'Filtered Result': 'Résultats d'après les filtres',
    'Save Filter': 'Sauvegarder le fltre',
    save_filter_hint: '',

    //edit 
    Warn_Lost_Data: 'Vous avez fait des modifications dans les données. Cliquez sur "Sauvegarder", autrement tous vos changements seront perdus.',     
    Warn_Lost_Data_On_Structure_Edit: 'Cliquer sur "Sauvegarder les données" pour enregsitrer les mofications ou "Annuler les modifications".<br>Les changements de structure sont enregistrés automatiquement - ils ne sont pas affectés par ce choix.',
    
    //manage db definitions    
    manageDefRectypes_edit_fields: 'Editer les champs',
    manageDefRectypes_edit_fields_hint: 'Cela ouvrira un enregistrement vierge en mode "modification de structure".<br>Astuce  : vous pouvez activer le mode "modification de structure" à tout moment pendant la saisie des données pour effectuer des changements structurels.',            
    manageDefRectypes_new_hint: 'Avant de définir de nouveaux types d'enregistrements (entités), nous vous suggérons de regarder du coté. '+
                    'des structures proposées par les modèles (bases de données Heurist publiées dans le catalogue dédié). '+
                    'Les bases de données possédant un ID inférieur à 1000 proposent des modèles réalisés par l'équipe Heurist. '
                    +'<br><br>'
    +'Ceci est tout particulièrement important pour les enregistrements de type "BIBLIOGRAPHIC" - les structures du modèle #6 ("Bibliographic definitions") sont ' 
    +'normalisées et optimisées pour assurer une compatibilité maximale avec des fonctions telles que la synchronisation avec Zotero, mais aussi le format Harvard ou encore entre entre bases de données.'                
                    +'<br><br>Utilisez le menu principal : Conception > Parcourir les modèles',
    manageDefRectypes_delete_stop: '<p>Le type d'enregistrement <b>[rtyName]</b> est utilisé par les champs suivants :</p>'
                + '[FieldList]'
                +'<p>Veuillez supprimer ces champs, ou cliquez sur les liens ci-dessous <br>pour modifier pour modifier le champ de base (modifiera tous les types d'enresgitrements qui l'utilise).</p>',
    manageDefRectypes_delete_warn: 'Êtes vous sûr de vouloir supprimer ce type d'enregistrement ?',
    manageDefRectypes_duplicate_warn: 'Voulez vous vraiment dupliquer ce type d'enregistrement ?',
    'Click to add new': 'Cliquez pour en ajouter un nouveau ',
    'Click to launch search for': 'Cliquez pour lancer la recherche ',
    'Click to edit record type': 'Cliquez pour éditer le type d'enregistrement',
    'Click to hide in lists': 'Cliquez pour masquer dans les listes',
    'Click to show in lists': 'Cliquez pour afficher dans les listes',
    'Duplicate record type': 'Dupliquer le type d'enregistrement',
    'List of fields': 'Liste des champs',
    manageDefRectypes_reserved: 'Ceci est un type d'enregistrement réservé, commun à toutes les bases Heurist. Il ne peut pas être supprimé.',
    manageDefRectypes_hasrecs: 'Pour autoriser la suppression, utiliser Explorer > Entités pour trouver et supprimer tous les enregistrement.',
    manageDefRectypes_delete: 'Cliquer pour supprimer ce type d'enregistrement',
    manageDefRectypes_referenced: 'Ce type d'enregistrement est lié à d'autres. Cliquer pour montrer les liens',
    manageDefRectypes_longrequest: 'Cela prend du temps... il est posible que la base de données ne soit pas joignable à l'adresse <url>. Nous essayons encore une dizaine de secondes.',
    'Filter by Group': 'filtrer par groupe',
    'Show All': 'Tout afficher',
    'Sort by': 'Trier par',
    'All Find': 'Искать',
    'Not finding the record type you require?': 'Vous ne trouvez pas le tyê d'enregistrement dont vous avez besoin ?',
    'Define new record type': 'Définir un nouveau type d'enregistrement',
    'Find by name, ID or concept code': 'Trouver par nom, ID ou code de concept',
    'Show record types for all groups': 'Montrer les types d'enregistrements pour tous les groupes',
    'All Groups': 'Tous les groupes',
    'All record type groups': '',
    'Edit Title Mask': 'Éditer le masque de titre',
    
    //my preferences
    'Define Symbology': 'Choix des symboles'',                
    'Define Heurist Theme': 'Choix du thème',
    'Configure Interface': 'Configurer l\'interface',
    'Mark columns to be visible. Drag to re-order': 'Cochez les colonnes qui doivent être visibles. Faites glisser pour réorganiser',
    
    //record add dialog    
    'Add Record': 'Ajouter un enregistrement',
    'Record addition settings': 'Paramètres d'ajout d'un enregistrement',
    'Permission settings': 'Paramètres des autorisations',
    'Save Settings': 'Sauvegarder les paramètres',
    'Add Record in New Window': 'Ajouter un enregistrement dans une nouvelle fenêtre',
    'Type of record to add': 'Type d\'enregistrement à ajouter',
    'Get Parameters': 'Voir les paramètres',
    'Select record type for record to be added': 'Sélectionner le type pour l'enregistrement à ajouter',
    'select record type': 'sélectionner le type d'enregistrement',
    add_record_settings_hint: 'Ces paramètres seront appliqués et mémorisés lorsque vous sélectionnerez un type d'enregistrement dans la liste.',
        
    //record actions dialogs
    'Processed records': 'Enregistrements traités',
    recordAction_select_lbl: 'Enregistrements concernés :',
    recordAction_select_hint: 'merci de sélectionner les enregistrements concernés...',    
        'All records': 'Tous les enregistrements',
        'Selected results set (count=': 'Seulement les enregistrements sélectionnés (nombre=',
        'Current results set (count=': 'Tous les résultats (nombre=',
        'only:': 'uniquement :',
    'Add or Remove Tags for Records': 'Ajouter ou supprimer des tags pour l'enregistrement',
        'Add tags': 'Ajouter des tags',
        'Remove tags': 'Supprimer les tags',
        'Bookmark': 'Marque-page',
        recordTag_hint0: 'Sélectionnez les tags qui doivent être ajoutés aux marque-pages pour les URL sélectionnées<br>',
        recordTag_hint1: 'Sélectionnez les tags qui doivent être ajoutés aux marque-pages pour la liste d'enregistrements choisis<br>',
        recordTag_hint2: 'Sélectionnez les tags qui doivent être ajoutés ou supprimés pour la liste d'enregistrements choisis<br>',
        recordTag_hint3: 'Les tags correspondants sont affichés pendant que vous tapez. Cliquez sur un tag proposé pour l'ajouter<br>
        Les tags non reconnus sont ajoutés automatiquement comme tags spéficiques à l'utilisateur <br>
        (les tags de groupe doivent être ajoutés par l'administrateur du groupe). Les tags peuvent contenir des espaces.',
        'No tags were affected': 'Aucun tag n'a été attribué',
        'Bookmarks added': 'Marque page ajouté',
        'Tags added': 'Tags ajoutés',
        'Tags removed': 'Tags supprimés',
    'Unbookmark selected records': 'Supprimer les marque-pages pour les enregistrements sélectionnés',    
        recordUnbookmark_hint: 'Select the scope of records with bookmarks to be removed.<br>'
            +'Any personal tags for these records will be detached <br>'
            +'These operation ONLY removes the bookmark from your resources, <br>'
            +'it does not delete the record entries<br>',
        'Remove Bookmarks': 'Suppprimer les marque-pages',
        'Bookmarks removed': 'Marque-pages supprimés',
    'Set Record Rating': 'Définir l'évaluation de l'enregistrement',
        'Set Rating': 'Définir une évaluation',
        'Please specify rating value': 'Merci d'entrer une valeur pour l'évaluation',
        'Rating updated': 'Évaluation mise à jour',
        'No Rating': 'Aucune évaluation',
    'Delete Records': 'Supprimer l'enregistrement',        
        
    //SERVER SIDE MESSAGES
    'Record type not defined or wrong': 'Type d\'enregistrement non défini ou faux',        
            
            
    //Client side error message
    Error_Title: 'Heurist',
    Error_Empty_Message: 'Aucun message d'erreur n'a été prévu. Merci de contacter l'équipe de développement de Heurist.',
    Error_Report_Code: 'Signaler ce code à l'équipe de développement de Heurist',
    Error_Report_Team: 'Si cette erreur survient régulièrement, merci de contacter votre administrateur système ou de nous contacter par mail (support[at]HeuristNetwork[dot]org) en décrivant les circonstances dans lesquelles est apparue l'erreur afin qu'une solution puisse être trouvée',
    Error_Wrong_Request: 'La valeur, le nombre et/ou les paramètres de la requête ne sont pas valides.',
    Error_System_Config: 'Ceci peut venir d'une interruption du réseau ou d'un système mal configuré. Si le problème persite, signalez le à votre administrateur système.',
    Error_Json_Parse: 'Il n'est pas possible de lire la réponse du serveur',

//---------------------- END OF TRANSLATION 2021-10-19


            'Upload/register new file': 'Uploader ou enregistrer un nouveau fichier',
            'Add File':'Ajouter un fichier',
            'Edit File': 'Éditer le fichier',
            'Personal Files':'Fichiers personnels',
            'Delete selected files': 'Supprimer les fichiers sélectionnés ',
    
    
};

