/**
* @package     Heurist academic knowledge management system
* @link        http://HeuristNetwork.org
* @copyright   (C) 2005_2020 University of Sydney
* @author      Artem Osmakov   <artem.osmakov@sydney.edu.au>
* @license     http://www.gnu.org/licenses/gpl_3.0.txt GNU License 3.0
* @version     4.0
*/

/*
* Licensed under the GNU License, Version 3.0 (the "License"); you may not use this file except in compliance
* with the License. You may obtain a copy of the License at http://www.gnu.org/licenses/gpl_3.0.txt
* Unless required by applicable law or agreed to in writing, software distributed under the License is
* distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied
* See the License for the specific language governing permissions and limitations under the License.
*/

regional['ru'] = {
    language: 'Langue',
    'Databases': 'Bases de données,
    'Design database': 'Concevoir une base de données,
    'Import data': 'Importer des données,
    'Files in situ': 'Dossiers in situ',
    'Report bug': 'Signaler un bug',
    'About': 'A propos...',
    'Confirmation':'Confirmation',
    'Info':'Info',

    'Register': 'S'inscrire',
    'Registration': 'Inscription',
    'Login': 'Connexion',
    'Please log in': 'Veuillez vous connecter,
    'Please contact to register':'Veuillez contacter le propriétaire de la base de donnée pour vous inscrire ',
    'Log out' : 'Déconnexion',
    'Manage': 'Gérer',
    'Sort': 'Trier',
    'Search': 'Chercher',
    'Search result': 'Résultat de recherche',
    'Merge': 'Fusionner ? Combiner?,
    'Rate': 'Оценить',
    'Relate to': 'Связать с',
    'Access': 'Accès',
    'Notify': 'Notifier',
    'Embed / link': 'Intégrer / lier',
    'Export': 'Exporter',
    'Import': 'Importer',


    'Username': 'Login,
    'Password': 'Mot de passe',
    'Remember me': 'Se souvenir de moi,
    'Forgotten your password?': 'Mot de passe oublié ?',
    'Click here to reset it': 'Réinitialiser votre mot de passe',
    'Enter your username OR email address below and a new password will be emailed to you.':'Saisissez votre login ou votre adresse e-mail de récuperation"
,
    'Reset password': 'Réinitialiser mot de passe',
    'Email to':'Contact',
    'User information has been saved successfully':'Les informations de l'utilisateur ont été sauvegardées avec succès',

    'Database': 'Base de données',
    'Select database': 'Choisir la base de données',
    'My User Info' : 'Mon profil utilisateur',
    'My Groups' : 'Mes groupes',
    'Manage Tags' : 'Gérer mes étiquettes',
    'Tags' : 'Étiquettes',
    'Manage Files': 'Gérer mes dossiers',
    'Manage Reminders' : 'Gérer mes rappels',
    'Set Ratings' : 'Définir mes notations',
    'No Rating': 'Aucune notation,

    'Name': 'Titre',
    'Description': 'Description',
    'Size': 'Taille',
    'Type': 'Type',

    'search': 'c hercher',
    'all records': 'среди всех записей',
    'my bookmarks': 'mes marque-pages',
    'in current': 'в текущем',
    'search option': 'варианты поиска',
    'search assistant': 'assistant de recherche',
    'Any record type': 'Любой тип записи',
    'Any field type': 'Tout type de champ',
    'Record type': 'Тип записи',
    'Field': 'Champ',
    'Contains': 'Contient',
    'Is': 'Est',
    'Sort By': 'Trier par',
    'Sort Ascending': 'Trier en ordre croissant',
    'fields':'champs',

    'add': 'ajouter',
    'Add New Record' : 'Добавить запись',
    'tags': 'êtiquettes',
    'share': 'partager',
    'more': 'plus',
    'edit': 'modifier',
    'options': 'options',

    'by name': 'par titre',
    'by usage': par usage',
    'by date': 'par date',
    'by size': 'par taille,
    'by type': 'par type',
    'marked': 'marqué',

    'list':'liste',
    'icons':'icônes',
    'thumbs':'vignettes',
    'thumbs3':'превью',

    'first':'premier',
    'previous':'précédent',
    'next':'suivant',
    'last':'dernier',
    'records per request':'записей в запросе',

    'Manage tags': 'Gérer mes tags',
    'Create new tag': 'Créer un nouveau tag,
    'Add Tag': 'Ajouter un tag',
    'Edit Tag': 'Éditer le tag',
    'Define new tag that replaces old ones': 'Définir un nouveau tag qui remplace les anciens,
    'Length of tag must be more than 2.': 'La longueur du tag doit être supériure à 2',
    'Assign selected tags': 'Assigner les tags selectionnés',
    'Personal Tags':'Mes tags personnels,
    'Delete selected tags': 'Supprimer les tags selectionnés',



    'Preferences' : 'Préférences',
    'Layout configuration file': Fichier de configuration de la mise en page',
    'Language':'Langue',
    'Theme':'Thème',
    'Open edit in new window':'Ouvrir la fenêtre d'édition',
    'When exiting record edit, prompt for tags if no tags have been set':'Перед сохранением предлагать определить ярлыки',
    'Reload page to apply new settings?':'Recharger la page pour appliquer les nouveaux paramètres ?',

    'Click to save current search':'Cliquez pour sauvegarder la recherche en cours,
    'My Bookmarks': 'Mes marque-pages,
    'My Searches': 'Mes recherches',
    'Predefined searches': 'Recherches prédefinies,
    'Recent changes': 'Changements récents,
    'All records': ',
    'All (date order)': 'Tous (ordonné par date)',
    'Edit saved search': 'Éditer la recherche sauvegardée,
    'Delete saved search': 'Supprimer la recherche sauvegardée,
    'Manage Saved Searches': 'Gérer mes recherches sauvegardées,
    'Create new saved search': 'Créer une nouvelle recherche sauvegardée',

    'Database Summary': 'Сводка базы данных',
    'RuleSets': 'Зависимости',


    'Delete? Please confirm': 'Удалить? Подвтердите',

    'select record': 'выберите запись',

    'Leave blank for no change': 'Оставьте пустым чтобы не менять пароль',
    'Passwords are different': 'Пароли различны',
    'Wrong email format': 'Неправильный формат адреса почты',
    'Wrong user name format': 'Недопустимы формат для имени пользовтеля',
    'Wrong password format': 'Недопустимый формат для пароля',
    'Missing required fields': 'Не опрделены обязательные поля',
    'length must be between': 'длина должна быть между',
    'required field': 'обязательное поле',
    
    //========================  2021_07_08 =======================

    //common words
    'Close': 'Закрыть',
    'Settings': 'Настройки',
    'Help': 'Помощь',
    'Error': 'Ошибка',
    'records': 'записей',
    'loading': 'загрузка',
    'preparing': 'подготовка',
    'explanations': 'объяснения',
    'Show data': 'Показать данные',
    'Actions': 'Операции',
    'Embed': 'Внедрить',
    'Clear': 'Очистить',
    'Warning': 'Внимание',    
    'Cancel': 'Отмена',
    'Record Info': 'Данные записи',
    'Add': 'Добавить',
    'Assign': 'Присвоить',
    'Apply': 'Применить',
    'Abort': 'Прервать',
    'Define': 'Определить',
    'Edit': 'Править',
    'Delete': 'Удалить',
    'Create': 'Создать',
    'Confirm': 'Подтверждение',
    'Proceed': 'Продолжить',
    'Continue': 'Продолжить',
    'Go': 'Начать',
    'Yes': 'Да',
    'OK': 'OK',
    'No': 'Нет',
    'Save': 'Сохранить',
    'Save data': 'Сохранить данные',
    'Ignore and close': 'Игнорировать и закрыть',
    'Drop data changes': 'Отменить изменения',
    'Manage': 'Управление',
    'Select': 'Выбор',
    'Configure': 'Конфигурация',
    
    'Show context help': 'Контекстная помощь',
    'Heurist context help': 'Контекстная помощь',
    'Sorry context help was not found': 'Помощь не найдена',
    
    //main menu 
    'Admin': 'Админ',
    'Design': 'Дизайн',
    'Populate': 'Наполнение',
    'Explore': 'Искать',
    'Publish': 'Публикация',
    'Profile': 'Профиль',
        
    add_new_record: 'Новая запись', //header for New record
    add_new_record2: 'Ввод', // prefix before rectype name
    
    //explore menu
    'Filters': 'Фильтры',
    'Recent': 'Недавние',
    'All': 'Все',
    'Entities': 'Типы записей',
    'Saved filters': 'Каталог фильтров',
    'Build': 'Создать',
    'Filter builder': 'Условия поиска',
    'Facets builder': 'Многогранный поиск',
    'Save filter': 'Добавить фильтр',
    'Advanced': 'Дополнительно',
    'Rules': 'Каскадный поиск',
    
    //admin menu
    'Database': 'База данных',
        menu_database_browse: 'Открыть',
        menu_database_create: 'Новая',
        menu_database_clone: 'Клонировать',
        menu_database_delete: 'Удалить',
        menu_database_clear: 'Очистить',
        menu_database_rollback: 'Восстановить',
        menu_database_register: 'Зарегистрировать',
        menu_database_properties: 'Свойства',
        
        menu_database_browse_hint:'Найти и открыть другую базу Heurist в новом окне',
        menu_database_create_hint:'Созадть новую базу данных _ все основные элементы структуры будут добавлены автоматически',
        menu_database_clone_hint:'Создать копию текущей базы со всеми данными, загружеными файлами, шаблонами итп',
        menu_database_delete_hint:'Удалить текущую базу полностью _ не может быть отменено, хотя данные будут скопированы в дамп и могут быть восстановлены сисадмином',
        menu_database_clear_hint:'Clear all data (records, values, attached files) from the current database. Database structure _ record types, fields, terms, constraints _ is unaffected',
        menu_database_rollback_hint:'Selectively roll back the data in the database to a specific date and time',
        menu_database_register_hint:'Зарегистировать эту базу в Heurist Master Index _ это сделает доступным импорт элементов структуры (но не данных) в других базах',
        menu_database_properties_hint:'Редактировать описание базы данных и определить некторые глобальные установить . Recommended to provide a self_documenting database',
        
    'Manage Users': 'Пользователи',
        menu_profile_groups: 'Группы',
        menu_profile_users: 'Пользователи',
        menu_profile_import: 'Импорт профиля',
        menu_profile_groups_hint: 'List of groups you are member of',
        menu_profile_users_hint: 'Add and edit database users, including authorization of new users. Use Manage Workgroups to allocate users to workgroups and define roles within workgroups',
        menu_profile_import_hint: 'Import users one at a time from another database on the system, including user name, password and email address _ users are NOT assigned to workgroups',
    'Utilities': 'Утилиты',
        menu_profile_files: 'Управление файлами',
        menu_profile_preferences: 'Настройки профиля',
        menu_structure_verify: 'Проверка целостности данных',
        menu_structure_duplicates: 'Найти повторения',
        menu_manage_rectitles: 'Обновить заголовки',
        menu_profile_files_hint: 'Управление загружеными файлами и удаленными медиа ресурсами',
        menu_profile_preferences_hint: 'Показать и редактировать настройки профиля',
        menu_structure_verify_hint: 'Найти ошибки в структуре базы (неправильные типы записей, полей и словарей) и записи с неправильной структурой и ошибными данными (ссылки, пропущеные данные итп)',
        menu_structure_duplicates_hint: 'Нечеткий поиск для определения записей которые могут содержать идентичные данные',
        menu_manage_rectitles_hint: 'Обновить заголовки для всех записей',
    'Server Manager': 'Управление сервером',
        menu_admin_server: 'Базы данных',
        menu_admin_server_hint: 'Операции для всех баз данных на этом сервере',
        
    //design menu
    'Modify': 'Изменить структуру',
        menu_structure_rectypes: 'Типы записей',
        menu_structure_vocabterms: 'Словари',
        menu_structure_fieldtypes: 'Базовые поля',
        menu_structure_import: 'Импорт шаблонов',
        menu_lookup_config: 'External lookups', // needs replacing
        menu_structure_summary: 'Визуализация',
        menu_structure_refresh: 'Перегрузить структуру',
    
        menu_structure_rectypes_hint: 'Добавить или модифицировать типы записей',
        menu_structure_vocabterms_hint: 'Добавить или модифицировать словари',
        menu_structure_fieldtypes_hint: 'Редактировать определения базовых полей используемых в типах записей (часто одновременно в нескольких типах)',
        menu_structure_import_hint: 'Выборочно импортировать типы записей, базовые поля и словари из других баз Heurist',
        menu_structure_summary_hint: 'Визуализация внутренних связей между типами записей в базе (указателей и отношений)',
        menu_structure_refresh_hint: 'Очистить и перегрузить структру базы Heurist в вашем браузере. Используйтк чтобы обновить списки и селекторы в случае если изменени не отображаются',
    
    'Setup': 'Настройки',
        menu_manage_dashboards: 'Панель ярлыков',
        menu_manage_archive: 'Архивировать базу',
        menu_manage_dashboards_hint: 'Определить ярлыки для быстрого доступа к функциям',
        menu_manage_archive_hint: 'Архивировать все данные как SQL дамп и XML файлы, а также загруженые файлы, шаблоны и документы, в ZIP архив который моэет быть скачен по ссылке',

    'Download': 'Скачать',
        menu_manage_structure_asxml: 'Структуру как XML',
        menu_manage_structure_assql: 'Структуру как Text',
        menu_manage_structure_asxml_hint: 'Список определений типов записи и полей в XML формате (HML - Heurist Markup Language)',
        menu_manage_structure_assql_hint: 'Список определений типов записи и полей в форме для использования SQL выражениях',
        
    //populate menu
    'Upload Files': 'Загрузить файлы',
        menu_import_csv: 'Текст / CSV',
        menu_import_zotero: 'Zotero библиография',
        menu_import_xml: 'Heurist XML/JSon',
        menu_import_kml: 'KML',
        menu_import_get_template: 'Скачать шаблон (XML)',
        menu_import_csv_hint: 'Import data from delimited text file. Supports matching, record creation, record update.',
        menu_import_zotero_hint: 'Synchronise with a Zotero web library _ new records are added to Heurist, existing records updated',
        menu_import_xml_hint: 'Import records from another database',
        menu_import_kml_hint: 'Import KML files (geographic data in WKT can be imported from CSV &amp; tab delimited files)',
        menu_import_get_template_hint: 'Get XML template that describes database structure', 
    'Media Files': 'Медиа файлы',
        menu_files_upload: 'Загрузить медиа файлы',
        menu_files_index: 'Проиндексировать',
        menu_files_upload_hint: 'Upload multiple files and/or large files to scratch space or image directories, delete and rename uploaded files',
        menu_files_index_hint: 'Index files on the server and create multimedia records for them (reads and creates FieldHelper manifests)',
    
    //publish menu
    'Website': 'Веб сайт',
        menu_cms_create: 'Создать',
        menu_cms_edit: 'Править',
        menu_cms_edit_new: 'Править (новое)',
        menu_cms_view: 'Просмотр',
        menu_cms_embed: 'Отдельная веб страница',
        menu_cms_create_hint: 'Create a new CMS website, stored in this database, with widgets to access data in the database',
        menu_cms_edit_hint: 'Edit a CMS website defined in this database',
        menu_cms_view_hint: 'View a CMS website defined in this database',
        menu_cms_embed_hint: 'Create or edit a standalone web page in this database. May contain Heurist widgets. Provides code to embed page in an external iframe.',
        
        'Website Editor': 'Редактор вебсайта',
        'Sitewide Settings': 'Настройки сайта',
        'Current Page': 'Текущая страница',
       'Page Editor': 'Редактор страницы',
       
    'Standalone page': 'Отдельная веб страница',
        menu_cms_create_page: 'Создать',
        menu_cms_edit_page: 'Править',
        menu_cms_view_page: 'Просмотр',
        
    'Export': 'Экспорт',
        menu_export_csv: 'CSV',
        menu_export_hml_resultset: 'XML',
        menu_export_json: 'JSON',
        menu_export_geojson: 'GeoJSON',
        menu_export_kml: 'KML',
        menu_export_gephi: 'GEPHI',
        menu_export_csv_hint: 'Export records as delimited text (comma/tab), applying record type',
        menu_export_hml_resultset_hint: 'Generate HML (Heurist XML format) for current set of search results (current query + expansion)',
        menu_export_json_hint: 'Generate JSON for current set of search results (current query)',
        menu_export_geojson_hint: 'Generate GeoJSON_T for current set of search results (current query)',
        menu_export_kml_hint: 'Generate KML for current set of search results (current query + expansion)',
        menu_export_gephi_hint: 'Generate GEPHI for current set of search results (current query + expansion)',
    
    'Safeguard': 'Резервная копия',
        
    //My profile menu
    menu_profile_tags: 'Управления тегами',
    menu_profile_reminders: 'Управление напоминаниями',
    menu_profile_info: 'Мой профиль',
    menu_profile_logout: 'Выход',
    menu_profile_tags_hint: 'Удаление, модификация, переименование ваших личных и групповых тегов (ярлыков)',
    menu_profile_reminders_hint: 'Просмотр и удаления автоматических сообщений/ссылок на ваши записи',
    menu_profile_info_hint: 'Информация о вашем пользовательском профиле',
    menu_profile_logout_hint: '',
        
    //HELP menu
    HELP: 'ПОМОЩЬ',
        menu_help_online: 'Документация',
        menu_help_website: 'Heurist Network вебсайт',
        menu_help_online_hint: 'Исчерпывающая помощь и документация по Heurist',
        menu_help_website_hint: 'Heurist Network вебсайт - основной источник  информации, услуг и контактов', 
    CONTACT: 'КОНТАКТЫ',
        menu_help_bugreport: 'Отчет об ошибке / запрос новых функций',
        menu_help_emailteam: 'Команда Heurist',
        menu_help_emailadmin: 'Системны администратор',
        menu_help_acknowledgements: 'Признательности',
        menu_help_about: 'О приложении',
        menu_help_bugreport_hint: 'Послать email to the Heurist team such as additional bug information, comments or new feature requests',
        menu_help_emailteam_hint: '',
        menu_help_emailadmin_hint: 'Послать email to the System Adminstrator for this installaton of Heurist - typically for probelms with this installation',
        menu_help_acknowledgements_hint: '',
        menu_help_about_hint: 'Версия, Авторы, Права, Лицензия',
    
    menu_subset_set: 'Подмножество',
    menu_subset_set_hint: 'Сделать текущий поиск активным - все последующие поиски будут проходить в этом подмножестве записей',
    'Click to revert to whole database': 'Нажмите чтобы сбросить подмножество и искать по всей базе',
    'SUBSET ACTIVE': 'ПОДМНОЖЕСТВО',
    'Current subset': 'Активно',
    
    //END main menu
    
    //resultList --------------------
    
    'Selected': 'Sélectionner',
        menu_selected_select_all: 'Tout sélectionner',
        menu_selected_select_all_hint: 'Sélectionner tous les enregistrements de la page (liste ?)',
        menu_selected_select_none: 'Déselectionner',
        menu_selected_select_none_hint: 'Déselectionner tous les enregistrements de la page (liste ?)',
        menu_selected_select_show: 'Afficher entant de résultat d'une requête',
        menu_selected_select_show_hint: 'Открыть отмеченые записи в новом окне',
        menu_selected_tag: 'Тег (ярлык)',
        menu_selected_tag_hint: 'Присвоить или удалить теги для отмеченых записей',
        menu_selected_rate: 'Оценить',
        menu_selected_rate_hint: 'Присвоить оценку (рейтинг)для отмеченых записей',
        menu_selected_bookmark: 'Избранные',
        menu_selected_bookmark_hint: 'Добавить отмеченые записи в "Избранное"',
        menu_selected_unbookmark: 'Отменить избранность',
        menu_selected_unbookmark_hint: 'Удалить отмеченые записи из "Избранное"',
        menu_selected_merge: 'Объеденить',
        menu_selected_merge_hint: 'Определить повторение данных и объеденить записи',
        menu_selected_delete: 'Удалить',
        menu_selected_delete_hint: 'Удалить отмеченые записи',
    'Collected': 'Выбрано',
    'Collect': 'Выбрано',
        menu_collected_add: 'Добавить',
        menu_collected_add_hint: 'Отметь записи и добавь в выбранные (коллекцию)',
        menu_collected_del: 'Убрать',
        menu_collected_del_hint: 'Отметьте записи и удалите из выбранных (коллекции)',
        menu_collected_clear: 'Очистить все',
        menu_collected_clear_hint: 'Убрать все записи из выбранных. Очистить коллекцию',
        menu_collected_save: 'Сохранить',
        menu_collected_save_hint: 'Сохранить коллекцию как фильтр',
        menu_collected_show: 'Как поиск',
        menu_collected_show_hint: 'Показать коллекцию как результат поиска',
            collection_limit: 'The number of selected records is above the limit in ',
            collection_select_hint:  'Отметьте по крайней одну запись для добавления в коллекцию',
            collection_select_hint2: 'Отметьте по крайней одну запись для удаления из коллекции',
            collection_url_hint: 'Collections are saved as a list of record IDs. The URL generated by this collection would exceed the maximum allowable URL length by of 2083 characters. Please save the current collection as a saved search (which allows a much larger number of records), or add fewer records.',
    
    'Recode': 'Recoder',
        menu_selected_value_add: 'Ajouter une valeur',
        menu_selected_value_add_hint: 'Ajouter une valeur pour les résultats trouvés',
        menu_selected_value_replace: 'Remplacer une valeur',
        menu_selected_value_replace_hint: 'Remplacer une valeur dans les enregistrements trouvés',
        menu_selected_value_delete: 'Supprimer une valeur',
        menu_selected_value_delete_hint: 'Supprimer une valeur dans les enresgitrements trouvés',
        menu_selected_add_link: 'Relier : lien',
        menu_selected_add_link_hint: 'Ajouter un nouveau lien ou créer une nouvelle relation entre des enregistrements',
        menu_selected_rectype_change: 'Changer le type d'enregistrement',
        menu_selected_rectype_change_hint: 'Changer le type d'enregistrement pour les enregistrements trouvés',
        menu_selected_extract_pdf: 'Extraire le texte d'un document PDF',
        menu_selected_extract_pdf_hint: 'Extract text from PDExtraire le texte d'un document PDF (expérimental)',
    'Shared': 'Partager',
        menu_selected_notify: 'Notification (courriel)',
        menu_selected_notify_hint: 'Sélectionner un ou plusieurs enregistrement puis cliquer pour envoyer une notification',
        menu_selected_email: 'Envoyer un courriel',
        menu_selected_email_hint: 'Envoyer un courriel aux personnes ou aux institutions décrites dans l'enregistrement sélectionné',
        menu_selected_ownership: 'Propriété / visibilité',
        menu_selected_ownership_hint: 'Sélectionner un Select one or more records, then click to set workgroup ownership and visibility',
    'Reorder': 'Réorganiser',
    menu_reorder_hint: 'Allows manual reordering of the current results and saving as a fixed list of ordered records',
    menu_reorder_title: 'Drag records up and down to position, then Save order to save as a fixed list in this order',
    menu_reorder_save: 'Save Order',
    
    //
    resultList_select_record: 'Merci de sélectionner au moins un enregistrement pour cette action',
    resultList_select_record2: 'Merci de sélectionner au moins deux enregistrement pour identifier ou fusionner des doublons',
    resultList_select_limit: 'Le nombre d'enregistrements sélectionnés est supérieur à la limite de ',
    resultList_noresult: 'Aucun résultat. Merci de modifier la recherche ou le filtre pour trouver au moins un enregistrement.',
    resultList_empty_remark: 'Aucun enregistrement ne correspond au critère (des enregistrements existent peut-être mais n'ont peut-être pas été rendus publics ou visible pour votre profil utilisateur)',
    resultList_private_record: 'Cet enregistrement n'est pas visible de manière publique - les utilisateurs doivent être connectés pour le voir',
    'private - hidden from non-owners': 'privé (masqué pour les non-propriétaires)',
    'visible to any logged-in user': 'visible pour tous les utilisateurs connectés',
    'pending (viewable by anyone, changes pending)': 'en cours (visible par tout le monde, changements en cours)',
    'public (viewable by anyone)': 'public (visible par tout le monde)',
    'show selected only': 'montrer uniquement la sélection',
    'Single lines': 'Lignes simples',
    'Single lines with icon': 'Lignes simples avec icône',
    'Small images': 'Petites images',
    'Large image': 'Grandes images',
    'Record contents': 'Contenu de l'enregistrement',
    resultList_view_content_hint1: 'Cette alerte se déclenche s'il y a plus de 10 enregistrements',
    resultList_view_content_hint2: 'Vous avez sélectionné',
    resultList_view_content_hint3: 'enregistrements. Ce mode d'affichage charge l'ensemble des informations pour chaque enregistrement. Le chargement et l'affichage de toutes ces informations peut prendre un temps important.',
    resultList_action_edit: 'Cliquer pour éditer l'enregistrement',
    resultList_action_edit2: 'Cliquer pour éditer l'enregistrement (s'ouvre dans un ouvel onglet)',
    resultList_action_view: 'Cliquer pour éditer l'enregistrement (s'ouvre dans un fenêtre pop-up)',
    resultList_action_view2: 'Cliquer pour suivre le lien externe (s'ouvre dans une nouvelle fenêtre)',
    resultList_action_map: 'Cliquer pour afficher/masquer sur la carte',
    resultList_action_dataset: 'Télécharger le jeu de données',
    resultList_action_embded: 'Cliquer pour incorporer',
    resultList_action_delete: 'Cliquer pour supprimer',
   
    resultList_action_delete_hint: 'Delete map document. Associated map layers and data sources retain',
    'Password reminder': 'Aide-mémoire pour le mot de passe',
   
    //END resultList

    //search - filters
    'Filter': 'Filtre',
    'Filtered Result': 'Résultatd d'après les filtres',
    'Save Filter': 'Sauvegarder le fltre',
    save_filter_hint: 'Сохранить текущий поиск как фильтр доступный для постоянного использования через меню',

    //edit 
    Warn_Lost_Data: 'Вы изменили данные. Нажмите "Сохранить", иначе потеряете все изменения.',     
    Warn_Lost_Data_On_Structure_Edit: 'Нажмите "Сохранить данные" чтобы сохранить запись, "Отменить изменения" чтобы отказаться.<br>Изменения в структуре типа данных будут сохраняться автоматически - это не зависит от Вышего выбора.',
    
    //manage db definitions    
    manageDefRectypes_edit_fields: 'Редактировать поля',
    manageDefRectypes_edit_fields_hint: 'Откроется редкатор пустой записи этого типа в режиме редактрирования структуры<br>Чтобы мгновенно изменить тип данных, Вы можете переключиться в режим редактирования<br> структуры в любое момент при правке ваших записей',            
    manageDefRectypes_new_hint: 'Прежде чем определять новы тип данных, мы предлагаем найти подходяший тип среди шаблонов '+
                    '(Базы Heurist которые зарегистрированы в центральном хранилище). '+
                    'Базы с индексом менее 1000 верифицируются командой Heurist. '
                    +'<br><br>'
    +'Это особенно важно для Библиографических типов данных (см. Шаблон #6 "Bibliographic definitions"), ' 
    +'которые оптимизированы и совместимы с библиографическими данными такими как Zotero, Harvard формат, а также поддерживают обмен данными между базами Heurist.'                
                    +'<br><br>В главном меню:  Дизайн > Импорт шаблонов',
    manageDefRectypes_delete_stop: '<p>Тип данных <b>[rtyName]</b> используется в следующих полях:</p>'
                + '[FieldList]'
                +'<p>Или удалите эти поля или нажмите на ссылке в списке <br>для правки базового поля (это повлияет на все типы данных которые используют это поле).</p>',    
    manageDefRectypes_delete_warn: 'Вы уверены что хотите удалить этот тип данных?',
    manageDefRectypes_duplicate_warn: 'Вы уверены что хотите дублировать тип данных ',
    'Click to add new': 'Cliquer pour ajouter un nouveau ',
    'Click to launch search for': 'Искать записи типа ',
    'Click to edit record type': 'Cliquer pour éditer le type d'enregistrement',
    'Click to hide in lists': 'Cliquer pour masquer dans les listes',
    'Click to show in lists': 'Cliquer pour afficher dans les listes',
    'Duplicate record type': 'Дублировать тип данных',
    'List of fields': 'Список полей',
    manageDefRectypes_reserved: 'Этот тип данных зарезервирован во всех базах Heurist. Он не может быть удален.',
    manageDefRectypes_hasrecs: 'Прежде чем удалить, нужно удалить записи этого типа. Искать > Типы записей чтобы найти и удалить все записи',
    manageDefRectypes_delete: 'Удалить этот тип данных',
    manageDefRectypes_referenced: 'Этот тип данных используется в базовых полях. Нажмите чтобы посмотреть эти поля',
    manageDefRectypes_longrequest: 'This is taking a long time, it is possible the database is not reachable at <url>, will keep trying for another <timeout - 5> seconds',
    'Filter by Group': 'filtrer par groupe',
    'Show All': 'Tout afficher',
    'Sort by': 'Trier par',
    'All Find': 'Искать',
    'Not finding the record type you require?': 'Vous ne trouvez pas le tyê d'enregistrement dont vous avez besoin ?',
    'Define new record type': 'Définir un nouveau type d'enregistrement',
    'Find by name, ID or concept code': 'Trouver par nom, ID ou code de concept',
    'Show record types for all groups': 'Montrer les types d'enregistrements pour tous les groupes',
    'All Groups': 'Tous les groupes',
    'All record type groups': 'ых из все групп',
    'Edit Title Mask': 'Éditer le masque de titre',
    
    //my preferences
    'Define Symbology': 'Определить стиль отрисовки',                
    'Define Heurist Theme': 'Défnir le thème',
    'Configure Interface': 'Configurer l\'interface',
    'Mark columns to be visible. Drag to re-order': 'Отметьте видимые поля. Установить порядок перетаскивая',
    
    //record add dialog    
    'Add Record': 'Ajouter un enregistrement',
    'Record addition settings': 'Настройки для новой записи',
    'Permission settings': 'Paramètres des autorisations',
    'Save Settings': 'Sauvegarder les paramètres',
    'Add Record in New Window': 'Ajouter un enregistrement dans une nouvelle fenêtre',
    'Type of record to add': 'Type d\'enregistrement à ajouter',
    'Get Parameters': 'Загрузить параметры',
    'Select record type for record to be added': 'Sélectionner le type pour l'enregistrement à ajouter',
    'select record type': 'sélectionner le type d'enregistrement',
    add_record_settings_hint: 'Эти настройки будут применяться для новых записей',
        
    //record actions dialogs
    'Processed records': 'Enregsitrements traités',
    recordAction_select_lbl: 'Диапазон записей:',
    recordAction_select_hint: 'выберите записи для операции …',    
        'All records': 'Tous les enregistremnts',
        'Selected results set (count=': 'Отмеченные записи (кол-во=',
        'Current results set (count=': 'Текущий результат поиска (кол-во=',
        'only:': 'только:',
    'Add or Remove Tags for Records': 'Ajouter ou supprimer des tags pour l'enregistrement',
        'Add tags': 'Ajouter des tags',
        'Remove tags': 'Supprimer les tags',
        'Bookmark': 'Marque-page',
        recordTag_hint0: 'Определите теги с которыми выбранные URL будут добавлены в избранные<br>',
        recordTag_hint1: 'Определите теги с которыми выбранные записи будут добавлены в избранное<br>',
        recordTag_hint2: 'Определите теги чтобы добавить или убрать для выбранных записей<br>',
        recordTag_hint3: 'Matching tags are shown as you type. Click on a listed tag to add it.<br>Unrecognised tags are added automatically as user-specific tags <br>(group tags must be added explicitly by a group administrator). Tags may contain spaces.',
        'No tags were affected': 'Aucun tag n'a été attribué',
        'Bookmarks added': 'Marque page ajouté',
        'Tags added': 'Tags ajoutés',
        'Tags removed': 'Tags supprimés',
    'Unbookmark selected records': 'Supprimer les marque-pages pour les enregistrements sélectionnés',    
        recordUnbookmark_hint: 'Выберите записи которые будут удалены из избранных.<br>'
            +'Любые персональные теги будут убраны из этих записей<br>'
            +'Эта операция удаляет только метку "избранности" и убирает теги из записей, <br>'
            +'собственно записи не удаляются<br>',
        'Remove Bookmarks': 'Suppprimer les marque-pages',
        'Bookmarks removed': 'Marque-pages supprimés',
    'Set Record Rating': 'Définir l'évaluation de l'enregistrement',
        'Set Rating': 'Définir une évaluation',
        'Please specify rating value': 'Merci d'entrer une valeur pour l'évaluation',
        'Rating updated': 'Évaluation mise à jour',
        'No Rating': 'Aucune évaluation',
    'Delete Records': 'Supprimer l'enregistrement',        
        
    //SERVER SIDE MESSAGES
    'Record type not defined or wrong': 'Type d\'enregistrement non défini ou faux',        
            
            
    //Client side error message
    Error_Title: 'Heurist',
    Error_Empty_Message: 'Сервер не предоставил текст сообщения об ошибке, пожалуйста сообщите об этом команде раработчиков Heurist.',
    Error_Report_Code: 'Cообщите код ошибки команде раработчиков',
    Error_Report_Team: 'Если эта ошибка случается регулярно, пожалуйста сообщите Вашему сисадмину или свяжитесь с нами (support at HeuristNetwork dot org) и опишите обстаятельства при которых появляется эта ошибка.',
    Error_Wrong_Request: 'Значения и/или количество параметров запроса неверны.',
    Error_System_Config: 'May result from a network outage, or because the system is not properly configured. If the problem persists, please report to your system administrator',
    Error_Json_Parse: 'Невозможно разобрать ответ сервера',

//---------------------- END OF TRANSLATION 2021-10-19


            'Upload/register new file': 'Uploader ou enregistrer un nouveau fichier',
            'Add File':'Ajouter un fichier',
            'Edit File': 'Éditer le fichier',
            'Personal Files':'Fichiers personnels',
            'Delete selected files': 'Supprimer les fichiers sélectionnés ',
    
    
};

